# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d5d856316da48e86ffd272b8b3efca910158175f0b4155d8367431f38d7f5b8bb3f9950525386a53cd7b7b283abc231120eecc2d754c3d8904af7cba89029e

test:
  secret_key_base: 5264e3a5fc6f5d1cde5486b758f91d35a597905b4d1aae58fad2a86e27e60b0e82454f0c971e80880f3ade0108d30b9dc0ad2b0d78ac7ebcb6c31fbfd409cba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
